WebApplication14/WebApplication14/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication14.Data;
using WebApplication14.Models;
using WebApplication14.Models.MyViewModels;
using WebApplication14.Services;

namespace WebApplication14.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly UploadFile _fileUploadService;

        public CompaniesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IHostingEnvironment environment, UploadFile fileUploadService)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
            _fileUploadService = fileUploadService;
        }



        // GET: Companies/Details/5
        public async Task<IActionResult> Detail(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            var company = await _context.Company.FirstOrDefaultAsync(m => m.Id == id);
            var comments = await _context.Comment.Where(c => c.CompanyId == company.Id).Include(c=>c.User).OrderByDescending(c=>c.DateCreate).ToListAsync();
            var images = await _context.Image.Where(c => c.CompanyId == company.Id).ToListAsync();
            if (user != null)
            {
                ViewBag.UserId = user.Id;
            }
            
            DetailsViewModel model = new DetailsViewModel
            {
                Id = company.Id,
                Comments = comments,
                Images = images,
                Name = company.Name,
                Description = company.Description,
                Foto = company.Foto,
                Rating = company.Rating
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Detail(DetailsViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            var company = await _context.Company.FirstOrDefaultAsync(m => m.Id == model.Id);
            if (model.Comment != null)
            {
                Comment comment = new Comment
                {
                    Rating = Convert.ToInt32(model.NewRating),
                    Description = model.Comment.Description,
                    DateCreate = DateTime.Now,
                    UserId = user.Id,
                    CompanyId = model.Id
                };
                
                company.CountOfVotes += 1;
                var rate = _context.Comment.Where(s=>s.CompanyId == company.Id).Select(s => s.Rating);
                company.Rating = (rate.Sum() + Convert.ToDouble(model.NewRating)) / company.CountOfVotes;
                _context.Add(comment);
            }

            if (model.newFoto != null)
            {
                var path = Path.Combine(_environment.WebRootPath, $"image\\{user.UserName}\\post");
                _fileUploadService.Upload(path, model.newFoto.FileName, model.newFoto);
                Image image = new Image
                {
                    UserId = user.Id,
                    CompanyId = company.Id,
                    Foto = $"image/{user.UserName}/post/{model.newFoto.FileName}"
                };
                _context.Add(image);
                company.CountFotos += 1;
            }   
            _context.Update(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCompanyViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                Company company = new Company
                {
                    UserId = user.Id,
                    Name = model.Name,
                    Description = model.Description,
                    DateCreate = DateTime.Now,
                    Rating = 0 ,
                    CountOfVotes = 0
                };
                _context.Add(company);
                await _context.SaveChangesAsync();
                var path = Path.Combine(_environment.WebRootPath, $"image\\{company.Name}\\post");
                _fileUploadService.Upload(path, model.Foto.FileName, model.Foto);
                company.Foto = $"image/{company.Name}/post/{model.Foto.FileName}";
                _context.Update(company);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }

            return View(model);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company.SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", company.UserId);
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Foto,DateCreate,UserId,Rating")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", company.UserId);
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .Include(c => c.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Company.SingleOrDefaultAsync(m => m.Id == id);
            _context.Company.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool CompanyExists(int id)
        {
            return _context.Company.Any(e => e.Id == id);
        }
    }
}

WebApplication14/WebApplication14/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList;
using WebApplication14.Data;
using WebApplication14.Models;

namespace WebApplication14.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private const int pageSize = 20;
        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string search_word, int page = 1)
        {
            ViewBag.Search_word = search_word;
            var companies = _context.Company.Where(u => u.Name != null);

            if (!string.IsNullOrWhiteSpace(search_word))
            {
                companies = companies.Where(u => u.Name.Contains(search_word) || u.Description.Contains(search_word));
            }


            IPagedList<Company> companiesForPages = companies.ToPagedList(page, pageSize);
            return View(companiesForPages);
 
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication14/WebApplication14/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

WebApplication14/WebApplication14/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

WebApplication14/WebApplication14/Views/Home/Index.cshtml
@model PagedList.IPagedList<Company>


<div  class="main-block">
    <h2>Все заведения</h2>
    <form action="" method="get" class="search">
        <input type="search" name="search_word" placeholder="поиск" value="@ViewBag.Search_word" class="input" />
        <input type="submit" name="" value="" class="submit" />
    </form>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-12 col-md-6 col-lg-3 title-card">
                <div class="card">
                    <a asp-action="Detail" asp-controller="Companies" asp-route-id="@item.Id"><img class="card-img-top" width="150" height="160" src="@item.Foto" alt="главное фото"></a>
                    <div class="title">
                        <a asp-action="Detail" asp-controller="Companies" asp-route-id="@item.Id"><h4>@item.Name</h4></a>
                        <p>@item.Description</p>
                    </div>
                    <div>
                        <small class="text-muted">(@item.Rating, @item.CountOfVotes голосов)</small>
                    </div>
                    <div>
                        <small class="text-muted">@item.CountFotos фотографий</small>
                    </div>
                </div>
            </div>

        }

    </div>
    <div>
        Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        из @Model.PageCount

        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("<<", "Index", new { page = 1, search_word = ViewBag.Search_word })
            @Html.Raw(" ")
            ;
            @Html.ActionLink("< Предыдущая", "Index", new { page = Model.PageNumber - 1, search_word = ViewBag.Search_word })
        }
        else
        {
            @:<<
            @Html.Raw(" ")
            ;
            @:< Предыдущая
        }

        @if (Model.HasNextPage)
        {
            @Html.ActionLink("Следующая >", "Index", new { page = Model.PageNumber + 1, search_word = ViewBag.Search_word })
            @Html.Raw(" ")
            ;
            @Html.ActionLink(">>", "Index", new { page = Model.PageCount, search_word = ViewBag.Search_word })
        }
        else
        {
            @:Следующая >
            @Html.Raw(" ")
            @:>>
        }
    </div>
</div>
<style>
    .main-block {
        text-align: center;
        margin-top: 40px;
    }
    .card {
        text-align: center;
    }

    .card p {
        word-wrap: break-word;
    }

    .card a {
        text-decoration: none;
        color: black;
    }

    .card h4 {
        font-weight: bold;
    }

    .title {
        display: inline-block;
        width: 80%;
        text-align: center;
    }

    .title-card {
        padding: 0;
    }

    .search {
        width: 20%;
        position: relative;
        margin-top: 20px;
    }

    .search input {
        border: none;
    }

    .search .input {
        width: 100%;
        padding: 8px 37px 9px 15px;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        box-shadow: inset 0 0 5px rgba(0,0,0,0.1), inset 0 1px 2px rgba(0,0,0,0.3);
        border-radius: 20px;
        background: #EEE;
        font: 13px Tahoma, Arial, sans-serif;
        color: #555;
        outline: none;
    }

    .search .input:focus {
        box-shadow: inset 0 0 5px rgba(0,0,0,0.2), inset 0 1px 2px rgba(0,0,0,0.4);
        background: #E8E8E8;
        color: #333;
    }

    .search .submit {
        position: absolute;
        top: 0;
        right: 0;
        width: 37px;
        height: 100%;
        cursor: pointer;
        background: url(https://lh4.googleusercontent.com/-b-5aBxcxarY/UAfFW9lVyjI/AAAAAAAABUg/gQtEXuPuIds/s13/go.png) 50% no-repeat;
        opacity: 0.5;
    }

    .search .submit:hover {
        opacity: 0.8;
    }

    input[type="search"] {
        -webkit-appearance: none;
    }
    form {
        margin-bottom: 20px;
        display: inline-block;
    }
    .row {
        margin-bottom: 20px;
    }

</style>